blank_issues_enabled: false
contact_links:
  - name: Create new issue
    url: https://support.qq.com/products/321980
    about: Please use the following link to create a new issue.
  - name: Patreon
    url: https://yuanshen.site/docs/support-us.html
    about: Love Genshin Map? Consider supporting us.
  - name: Open Collective
    url: https://opencollective.com/genshinmap
    about: Love Genshin Map? Please consider supporting us via Open Collective.
